### ISSUE TITLE
State of branches for uni v3

### ISSUE THREAD

**Issue by pinouchon** [CoinAlpha/gateway-api#106]
Hello,

I would like to experiment with a uni v3 bot using gateway API. What branch should I be using?
Can you say what is the purpose of each branch and which one is stable/working ?

I'm thinking about the following branches: 
 - master
 - feat/improve_uni_v3_fee_responses
 - feat/uni_v3_ite-2

I noticed that in feat/uni_v3_ite-2, removePosition has been replaced by reducePosition. So I guess you can only reduce your liquidity and never close the position. Is that an issue?

Thanks in advance

**Comment by vic-en** [comment]
feat/improve_uni_v3_fee_responses is the latest and will be merged to development branch soon.
You can equally run with development branch of gateway-api when https://github.com/CoinAlpha/gateway-api/pull/103 is merged.

I'll be closing this ticket because its neither a request nor a bug.

Subsequently, kindly ask questions on our discord channel. 
Thanks.
